{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "il.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  strategy: {type: Recreate}
  selector:
    matchLabels:
      {{- include "il.selector" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "il.selector" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - {name: redis, containerPort: 6379}
          readinessProbe:
            exec: {command: ["redis-cli", "ping"]}
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "il.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    {{- include "il.selector" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - {name: redis, port: 6379, targetPort: redis}
{{- end }}
