{{- if not .Values.provider.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-provider
  labels:
    {{- include "il.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.provider.secretKey }}: {{ .Values.provider.apiKey | quote }}
{{- end }}
